FROM ubuntu:22.04 AS build

ARG RUNNER_IMAGE_VERSION=20250901.41
ARG ARM64=false
ARG MINIMAL=false
ARG SLIM=false

RUN --mount=source=ubuntu-22.04/setup-as-root.sh,target=/setup-as-root.sh /setup-as-root.sh

USER runner
WORKDIR /tmp

RUN --mount=source=ubuntu-22.04/build-as-runner.sh,target=/build-as-runner.sh /build-as-runner.sh $RUNNER_IMAGE_VERSION $ARM64 $MINIMAL $SLIM

COPY --chmod=555 common/entrypoint.sh /entrypoint.sh
COPY --chmod=555 common/start-docker.sh /start-docker.sh
COPY --chmod=555 common/job-started.sh /job-started.sh
COPY --chmod=555 common/job-completed.sh /job-completed.sh
COPY --chmod=555 common/publish-event.sh /publish-event.sh

FROM scratch AS image

ARG RUNNER_IMAGE_VERSION

ENV DEBIAN_FRONTEND=noninteractive
ENV RUNNER_MANUALLY_TRAP_SIG=1
ENV ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT=1
ENV ImageOS=ubuntu22
ENV ACTIONS_RUNNER_HOOK_JOB_STARTED=/job-started.sh
ENV ACTIONS_RUNNER_HOOK_JOB_COMPLETED=/job-completed.sh
ENV SPRINTERS_RUNNER_WEBHOOK=https://console.sprinters.sh/runner/webhook

LABEL org.opencontainers.image.source=https://github.com/sprinters-sh/sprinters-images
LABEL org.opencontainers.image.description="sprinters.sh runner"
LABEL org.opencontainers.image.licenses=MIT
LABEL sh.sprinters.runner-image.version=$RUNNER_IMAGE_VERSION

COPY --from=build / /

USER runner
WORKDIR /home/runner
ENV HOME=/home/runner

# Quick sanity check ensuring the runner is fully functional
RUN ./config.sh --version

CMD ["/entrypoint.sh"]
