name: minimal

on: workflow_dispatch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_NAME: Dockerfile-minimal

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from Dockerfile
        run: |
          VERSION=$(grep 'ARG RUNNER_VERSION=' "$DOCKERFILE_NAME" | cut -d '=' -f2)
          echo "RUNNER_VERSION: ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          file: ${{ env.DOCKERFILE_NAME }}
          build-args: RUNNER_VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sprinters-sh/sprinters-images-minimal:latest
            ghcr.io/sprinters-sh/sprinters-images-minimal:${{ env.VERSION }}
