name: ubuntu-24.04

on:
  push:
    paths-ignore:
      - .github/workflows/*.yml
      - images/Dockerfile-ubuntu-22.04
      - images/ubuntu-22.04/*.sh
      - images/*.cmd
      - README.md
      - LICENSE

jobs:
  ubuntu-2404:
    uses: ./.github/workflows/.ubuntu.yml
    with:
      ubuntu-version: 24.04
      arm64: false
      minimal: false
      slim: false
      instance: m8id.xlarge:ubuntu-24.04-minimal
