name: ubuntu-24.04-slim

on:
  push:
    paths-ignore:
      - .github/workflows/*.yml
      - images/*.cmd
      - README.md
      - LICENSE

jobs:
  ubuntu-2404-slim:
    uses: ./.github/workflows/.ubuntu.yml
    with:
      ubuntu-version: 24.04
      arm64: false
      minimal: false
      slim: true
      instance: m8id.xlarge:ubuntu-24.04-minimal
