name: ubuntu-22.04-slim

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/*.yml
      - images/Dockerfile-ubuntu-24.04
      - images/ubuntu-24.04/*.sh
      - images/*.cmd
      - README.md
      - LICENSE

jobs:
  ubuntu-2204-slim:
    uses: ./.github/workflows/.ubuntu.yml
    with:
      ubuntu-version: 22.04
      arm64: false
      minimal: false
      slim: true
      instance: m8id.xlarge:ubuntu-24.04-minimal
